FROM centos:centos6
ENV container docker

#RUN yum -y swap -- remove fakesystemd -- install systemd systemd-libs
#RUN yum -y update; yum clean all

RUN yum install -y wget dhclient
RUN yum install -y wget openssh-server
RUN yum install -y wget openssh-clients
RUN yum install -y wget nfs-utils nfs-utils-lib

#RUN yum -y swap -- remove fakesystemd -- install systemd systemd-libs
#RUN yum -y install nfs-utils; yum clean all
#RUN systemctl mask dev-mqueue.mount dev-hugepages.mount \
# systemd-remount-fs.service sys-kernel-config.mount \
# sys-kernel-debug.mount sys-fs-fuse-connections.mount
#RUN systemctl mask display-manager.service systemd-logind.service
#RUN systemctl disable graphical.target; systemctl enable multi-user.target

# Copy the dbus.service file from systemd to location with Dockerfile
#COPY dbus.service /usr/lib/systemd/system/dbus.service

#COPY auto.branchtest /etc/ - > copying this during container creation

#VOLUME ["/sys/fs/cgroup"]
#VOLUME ["/run"]

#CMD ["/usr/lib/systemd/systemd"]

# Make mount point
#RUN mkdir /docker-nfs

# Configure autofs - keep autofs optional
#RUN yum install -y autofs
#RUN echo "/docker-nfs /etc/auto.misc --timeout=50" >> /etc/auto.master

###### CONFIGURE THIS PORTION TO YOUR OWN SPECS ######
#RUN echo "docker -fstype=nfs4,minorversion=1,rw,nosuid,hard,tcp,timeo=60 10.228.225.142:/docker" >> /etc/auto.misc
######################################################

RUN mkdir /var/run/sshd
RUN echo 'root:abc123' | chpasswd
RUN sed -i 's/#PermitRootLogin without-password/PermitRootLogin yes/' /etc/ssh/sshd_config

# SSH login fix. Otherwise user is kicked off after login
RUN sed 's@session\s*required\s*pam_loginuid.so@session optional pam_loginuid.so@g' -i /etc/pam.d/sshd

ENV NOTVISIBLE "in users profile"
RUN echo "export VISIBLE=now" >> /etc/profile

EXPOSE 22
CMD ["/usr/sbin/sshd", "-D"]

# install pipework
RUN wget -N -P /opt/bin/ https://raw.githubusercontent.com/jadhavhninad/pipework/master/pipework
RUN chmod +x /opt/bin/pipework


# Copy the shell script to finish setup
#COPY configure-nfs.sh /configure-nfs.sh
#RUN chmod 777 configure-nfs.sh
